### ISSUE TITLE
[BUG] Link on site appears broken

### ISSUE THREAD

**Issue by snazy** [polaris-catalog/polaris#62] opened 2024-08-01 18:11 UTC
On the "Overview" page, I see this
![image](https://github.com/user-attachments/assets/2167d04e-9a39-47a8-b9af-0122b2c4a097)
but the markdown in `overview.md` is fine: `For example, to install Java 21 via [homebrew](https://brew.sh/) and `

**Comment by annafil** [comment] 2024-08-01 22:41
Docs need to be regenerated using redocly anytime we make a change to the markdown. Working on getting that automated, but in the meantime these instructions should help anyone who wants to start a PR to close this issue :) https://github.com/polaris-catalog/polaris/blob/main/README.md#api-docs

Going to mark this as a good first issue to encourage folks to contribute

**Comment by snazy** [comment] 2024-08-02 07:12
I suspect it's a bug in the redocly tool, because it looks the same when the site's regenerated :(

**Comment by annafil** [comment] 2024-08-02 16:23
Oh interesting!! Let me take a look then

**Comment by sfc-gh-suykumar** [comment] 2024-08-06 21:50
I am unable to reproduce the issue. Link doesn't seem to be broken for me here. https://polaris.io/index.html#section/Quick-Start/Prerequisites

Is this still an issue?

**Comment by suyashkumar2409** [comment] 2024-08-06 21:51
I am unable to reproduce the issue. Link doesn't seem to be broken for me here. https://polaris.io/index.html#section/Quick-Start/Prerequisites

Is this still an issue?

**Comment by collado-mike** [comment] 2024-08-08 18:54
Looks like this is fixed

**Closed by collado-mike** 2024-08-08 18:54 UTC
Labels: bug, good first issue
